spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**

        - id: product-service-swagger
          uri: lb://product-service
          predicates:
            - Path=/product-service/v3/api-docs/**

        - id: customer-service-swagger
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/v3/api-docs/**

        - id: order-service-swagger
          uri: lb://order-service
          predicates:
            - Path=/order-service/v3/api-docs/**

        - id: inventory-service-swagger
          uri: lb://inventory-service
          predicates:
            - Path=/inventory-service/v3/api-docs/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true
